on:
  push:
    branches:
      - "actions"
name: DeploytoSalesforceProduction
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: Install Dependencies
        run: |
          npm install -g sfdx-cli
          #npm install gfarb/sfdx-deploy@v1

      - name: SFDX Auth
        env:
          SFDX_JWT_KEY: ${{ secrets.SFDX_JWT_KEY }}
          SFDX_CLIENT_ID: ${{ secrets.SFDX_CLIENT_ID }}
        run: |
          echo "${SFDX_JWT_KEY}" > server.key
          npx sfdx force:auth:jwt:grant --clientid "${SFDX_CLIENT_ID}" --jwtkeyfile "${SFDX_JWT_KEY}" --username nitin.rajput@fexle.com.training.staging --setdefaultdevhubusername
          npx sfdx force:org:display --json -u nitin.rajput@fexle.com.training.staging > sfdx-auth.json
          rm server.key
          

      - name: Build, Test & Deploy
        uses: gfarb/sfdx-deploy@v1
        env:
          TARGET_USERNAME: nitin.rajput@fexle.com.training.staging
          SOURCE_PATH: force-app
          DESTRUCTIVE_CHANGES: destructive-changes
          TEST_LEVEL: RunLocalTests
          WAIT: 200
